import './globals.css'
import 'react-toastify/dist/ReactToastify.css';

import {Roboto} from 'next/font/google'
import {clsx} from "clsx";
import ToastifyProvider from "@/shared/providers/toastify.provider";
import Header from "@/shared/ui/layout/header";

const roboto = Roboto({weight: ['400', '700'], subsets: ['latin'], style: ["normal", "italic"]})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body suppressHydrationWarning className={clsx(roboto.className, 'flex flex-col grow')}>
        <ToastifyProvider>
            <Header/>
            <main className="flex flex-col grow">
                {children}
            </main>

        </ToastifyProvider>
        </body>

        </html>
    )
}
